Feature/create_googleform
HARUKINEMA/ki-wi pull request #123
Opened 2022-01-11 07:21 UTC by SC-bee

2022-01-11 08:46 UTC, Issei0804-ie requested changes
今あるボタンを押したらフォームに飛ぶように置き換えてくださいー

2022-01-11 08:51 UTC, SC-bee commented
OK

2022-01-12 01:47 UTC, SC-bee commented
置き換えました

2022-01-12 14:52 UTC, Issei0804-ie commented
@SC-bee CI 落ちてて deployment の確認ができないから、処理してくださいー！
es-lint で落ちてました。

2022-01-14 04:40 UTC, SC-bee commented
CI通したと思うので確認頼みます

2022-01-17 14:25 UTC, Issei0804-ie approved these changes

2022-01-17 14:43 UTC, merged