共通教育棟周辺の自販機を画像で見ることができる
HARUKINEMA/ki-wi pull request #68
Opened 2021-11-05 06:02 UTC by SoyaUehara

2021-11-06 03:50 UTC, Issei0804-ie requested changes
syntax,系のプラグインとか入ってなければ入れてくだし
https://www.google.com/search?q=vscode+typescript+syntax+highlighting

2021-11-06 03:50 UTC, Issei0804-ie commented on src/AreaContainer.tsx
> +      selectAreabutton,
=> selectAreaButton

2021-11-06 11:34 UTC, SoyaUehara commented
一応、直しはするけどそのコード何？
知らない。

2021-11-08 06:02 UTC, HARUKINEMA approved these changes
確認
OK

2021-11-08 10:13 UTC, Issei0804-ie approved these changes

2021-11-08 10:13 UTC, merged