card使用の可否で検索がかけられるようになりました
HARUKINEMA/ki-wi pull request #69
Opened 2021-11-05 16:50 UTC by HARUKINEMA

前バージョンのselectMarkers()とは中身が変わってるから確認してほしい
カード利用できるのは共通側の1個しかないです

2021-11-08 10:33 UTC, Issei0804-ie requested changes
とりあえず、 typo の指摘はオートマチックにやってほしいので、vscode のプラグイン入れるなりなんなりしてほしいです。

あと SelectMarkers に関してはコード短くするために詰め込んだんだと思うんですけど、逆に読むコストがかかっちゃうので、あのパターンは関数分けたほうがいいです。

そこの匙加減は難しいと思いますが、他の人が読みやすいかどうか、とか考えるといいかなぁと思います。

2021-11-08 10:33 UTC, Issei0804-ie commented on src/component/RadioButton.tsx
> +export enum Building {
RadioButton.tsx と関係ないので、 AreaRadioButton.tsx に移してほしいです！

2021-11-08 10:33 UTC, Issei0804-ie commented on src/component/RadioButton.tsx
> +export enum Card {
RadioButton.tsx と関係ないので CardRadioButton.tsx に移してほしいです！

2021-11-08 10:33 UTC, Issei0804-ie commented on src/component/CardRadioButton.tsx
> +  CardonChanged: (card: Card) => void;
typo

2021-11-08 10:33 UTC, Issei0804-ie commented on src/CardContainer.tsx
> +  CardonChangeRadioButton: (card: Card) => void;
on=>On

2021-11-08 10:33 UTC, Issei0804-ie commented on src/CardContainer.tsx
> +  CardonChange: (card: Card) => void
typo

2021-11-08 10:33 UTC, Issei0804-ie commented on src/CardContainer.tsx
> +    const selectCardbutton = props.cardRadioButtons.map((cardRadioButton) => {
Cardbutton => CardButton

2021-11-08 10:33 UTC, Issei0804-ie commented on src/AreaContainer.tsx
> +      selectAreabutton,
selectAreabutton => selectAreaButton

2021-11-08 10:33 UTC, Issei0804-ie commented on src/App.tsx
> +  const [nSize, nSetSize] = useState<number>(17);
magic number ではなく、const とかで定数宣言したほうがいいですねー。
多分根間君が書いてないと思うけど、直しちゃってください。

2021-11-08 10:33 UTC, Issei0804-ie commented on src/App.tsx
>    function SelectMarkers(
SelectMarkersByArea と SelectMarkersByCard などの2つの関数に分けてほしいです。

2021-11-08 10:33 UTC, Issei0804-ie commented on src/App.tsx
> +  const CardonChange = (card: Card) => {
typo

2021-11-08 10:33 UTC, Issei0804-ie commented on src/App.tsx
> +  const CardcheckBoxProps: CardContainerProps = {
radio button の props なので cardRadioButtonProps とかのほうが良さそう

2021-11-08 13:16 UTC, Issei0804-ie commented
あと area 選択 のラジオボタンに文字が近すぎるので離した方がいいですね．
![image](https://user-images.githubusercontent.com/52270000/140748428-dd0fd342-d079-409c-b628-352c4953c950.png)

2021-11-08 14:28 UTC, HARUKINEMA commented on src/App.tsx
>    function SelectMarkers(
これに関しては今後Select~~みたいな関数が増えていくと思っていて,なのでこのSelectMarkersが他のselect~~を呼び出す感じを考えている(and検索だとその方がやりやすそう)SelectMarkersByArea と SelectMarkersByCardに関しては次のPBIでやりたいと思っているんだけどどうかな?SelectMarkers()に統一したのじゃそういう意図です

2021-11-08 14:33 UTC, HARUKINEMA commented on src/App.tsx
> +  const CardcheckBoxProps: CardContainerProps = {
↓の文字が近いやつに関しても正直別PBIな気はするそんなめんどくさくもなさそうだけどこのPRではひとまず置いておきたい

2021-11-08 14:38 UTC, HARUKINEMA commented on src/App.tsx
>    function SelectMarkers(
SelectMarkersByCard()とSelectMarkersByArea()は今別のタイミングで実行されてて(1度に2箇所のラジオボタンは押せないので),なので実行する関数を統一してその中で「Areaを検索するときにCardの検索条件も確認してからSelectMarkerする」という処理にすることで実装しようと考えていて,そうなるともう親としてSelectMarkerに統一した方が描きやすいし追いやすいよねって思考です。今回は検索条件まだ少ないのでそのままSelectMarkerしている

2021-11-08 14:50 UTC, HARUKINEMA commented on src/App.tsx
> +  const [nSize, nSetSize] = useState<number>(17);
useState<number>(17)の17を直接指定するなって意味だと思うんだけどnSizeの名前をわかりやすく変えるとかの方が良くない?
定数として用意する意味をよくわかってないので教えてほしいです(コード書き換えるのが危ないからとか?)
nSizeが現状Mapのpropsとしてしか使ってないのでMapsizeに名前変えたいんだけど他に使う用途があって定数としてほしい場合は教えてほしいです

2021-11-08 14:59 UTC, HARUKINEMA commented on src/App.tsx
>    function SelectMarkers(
SelectMarker()の中で順番に「SelectMarkersByCard()とSelectMarkersByArea()を呼び出す」って感じで考えてる。好きなSelect...()作ってSelectMarker()の中にぶち込むだけなのでそんなでもないかなと思ってるんだけどどう?(現時点でちゃんとその形になってないんのでそこは結局直すけど)

2021-11-08 15:02 UTC, Issei0804-ie commented on src/App.tsx
> +  const [nSize, nSetSize] = useState<number>(17);
多分これ zoom の倍率を表してる数字じゃない...?
という感じでこれがなんの数字なのかわからなくなるので const にしたいと思いました．
ただ， nSize っていう変数名を変えて良さそうです!!!

2021-11-08 15:03 UTC, Issei0804-ie commented
あと，ラジオボタンの"ダメ"は "使用不可" とかの方がわかりやすそう！

2021-11-09 08:40 UTC, SC-bee reviewed
okです

2021-11-09 10:04 UTC, HARUKINEMA commented
一通り直したので確認してほしい新しい検索条件つけるときは
1.    drinkingmachine.jsonに新しい属性追加
2.   新しい〇〇Select()追加
3.   新しい〇〇RadioButton.tsx,〇〇Container.tsx追加
4.   コード中のコメントに従ってSelectMarkers()その他に追記
って感じを想定してます。
表示したいMarkerをidでtmpMarker:number[]として管理して,〇〇Select()でtmpMarkerをフィルターした後,最後まで残ったものを表示って感じにしてます(無駄な処理多いかもしれんが現時点だと気にするほど重くならない)

2021-11-10 01:56 UTC, Issei0804-ie requested changes

2021-11-10 01:56 UTC, Issei0804-ie commented on README.md
> +- 検索フォームからカード仕様の可否を検索条件に加えられるようになりました.
仕様 => 使用

2021-11-10 14:26 UTC, Issei0804-ie approved these changes
![](https://media.giphy.com/media/3ornjKv4yWgPJdYT8A/giphy.gif)

2021-11-10 14:29 UTC, merged