工学部棟1号館1階 & 工学棟3号館裏側 の自動販売機で販売されている飲み物の商品名を追加
HARUKINEMA/ki-wi pull request #81
Opened 2021-11-16 08:37 UTC by Issei0804-ie

close #78

2021-11-26 04:50 UTC, HARUKINEMA approved these changes
OK

2021-11-26 05:17 UTC, SoyaUehara requested changes
修正お願いします

2021-11-26 05:17 UTC, SoyaUehara commented on src/drinking_machine.json
> +        "午後の紅茶 ストレートティー ",
後ろに空白が入ってる

2021-11-26 05:24 UTC, Issei0804-ie commented on src/drinking_machine.json
> +        "午後の紅茶 ストレートティー ",
修正しましたー

2021-11-26 05:27 UTC, SoyaUehara approved these changes
確認しました。OKです。

2021-11-26 05:27 UTC, SoyaUehara commented
マージします。

2021-11-26 05:27 UTC, merged

2021-11-30 07:31 UTC, Issei0804-ie commented
close #78

2021-11-30 07:31 UTC, Issei0804-ie commented
open #78