商品検索(仮)機能の追加(商品名を入力して検索)
HARUKINEMA/ki-wi pull request #82
Opened 2021-11-26 04:51 UTC by SoyaUehara

2021-11-26 04:58 UTC, Issei0804-ie requested changes
修正お願いします！

2021-11-26 04:58 UTC, Issei0804-ie commented on src/App.test.tsx
> +  expect(ProductSelect("コーラ", [0, 1], machines)).toStrictEqual([0]);
下記のテストもお願いしますー
```
// 商品名の後に空白(半角)
expect(ProductSelect("コーラ ", [0, 1], machines)).toStrictEqual([0]);

// 商品名の後に空白(半角)
expect(ProductSelect("コーラ　", [0, 1], machines)).toStrictEqual([0]);

// 空白多め
expect(ProductSelect("     ", [0, 1], machines)).toStrictEqual([0]);
```

2021-11-26 04:58 UTC, Issei0804-ie commented on src/App.tsx
>    const CardOnChange = (card: Card) => {
typo

2021-11-28 07:32 UTC, HARUKINEMA approved these changes
OK

2021-11-28 07:34 UTC, Issei0804-ie approved these changes
![](https://media.giphy.com/media/26FPBpPPlwJ8WnLS8/giphy.gif)

2021-11-28 07:34 UTC, merged